FROM python:3.9-slim

WORKDIR /app

COPY requirements/requirements_offline.txt .
RUN pip install --no-cache-dir -r requirements_offline.txt

COPY . .

CMD ["python", "scripts/offline/main_offline_pipeline.py"]