# ============================================================================
# REDIS CACHE CONFIGURATION
# ============================================================================

connection:
  host: "localhost"
  port: 6380
  db: 0
  password: null
  decode_responses: false  # For binary data (embeddings)
  max_connections: 50
  socket_timeout: 5
  socket_connect_timeout: 2
  retry_on_timeout: true
  health_check_interval: 30

# ============================================================================
# TTL (Time To Live) SETTINGS
# ============================================================================
ttl:
  # Embeddings (binary data)
  user_embedding: 604800          # 7 days
  post_embedding: 2592000         # 30 days
  
  # CF Similarities
  cf_user_similarity: 86400       # 1 day
  cf_item_similarity: 86400       # 1 day
  
  # Statistics
  user_stats: 86400               # 1 day
  author_stats: 86400             # 1 day
  post_stats: 3600                # 1 hour
  
  # Real-time data
  following_list: 3600            # 1 hour
  following_posts: 1800           # 30 minutes
  trending_posts: 300             # 5 minutes
  user_recent_interactions: 3600  # 1 hour
  
  # Feed cache
  user_feed: 300                  # 5 minutes
  seen_posts: 86400               # 1 day

# ============================================================================
# KEY NAMING PATTERNS
# ============================================================================
key_patterns:
  # Embeddings
  user_embedding: "user:{user_id}:embedding"
  post_embedding: "post:{post_id}:embedding"
  
  # CF Similarities
  cf_user_similar: "cf:user:{user_id}:similar"
  cf_post_similar: "cf:post:{post_id}:similar"
  
  # Statistics
  user_stats: "stats:user:{user_id}"
  author_stats: "stats:author:{author_id}"
  post_stats: "stats:post:{post_id}"
  
  # Real-time data
  following_list: "following:{user_id}:list"
  following_posts: "following:{user_id}:posts"
  trending_posts: "trending:posts:{hour}"
  user_interactions: "user:{user_id}:interactions:recent"
  
  # Feed
  user_feed: "feed:{user_id}"
  seen_posts: "user:{user_id}:seen"

# ============================================================================
# CACHE WARMING STRATEGY
# ============================================================================
warmup:
  enabled: true
  on_startup: true
  
  # What to warm up
  strategies:
    - name: "active_users"
      description: "Warm up cache for recently active users"
      lookback_hours: 24
      max_users: 10000
    
    - name: "trending_posts"
      description: "Cache trending posts"
      refresh_interval_minutes: 5
    
    - name: "popular_authors"
      description: "Cache popular authors' recent posts"
      top_n_authors: 1000

# ============================================================================
# BATCH OPERATIONS
# ============================================================================
batch:
  pipeline_size: 1000
  chunk_size: 500

# ============================================================================
# MONITORING
# ============================================================================
monitoring:
  enabled: true
  metrics:
    - hit_rate
    - miss_rate
    - latency
    - memory_usage
  
  alerts:
    memory_threshold_mb: 4096
    hit_rate_threshold: 0.80